### PR TITLE
build: use npm prepare script to build the package on install #minor

### PR DESCRIPTION
**Pull request by aris-fm**
With this PR we can ignore `build` directory and instead build the package upon installation. 

Edit: To test this PR in AP change the dependency URL of `justice-js-common-utils` in `package.json` to this:
`git+https://github.com/aris-fm/justice-js-common-utils.git#use-prepare-script`

### CODE REVIEW

**Comment by rayhan-ab** [comment]
a lot of changed files here. could you tell us which files actually need review?

**Comment by aris-fm** [comment]
@rayhan-ab ah yes there are a lot of changes because I delete the entire `build` directory. The files that need to be reviewed are `package.json` and `.gitignore`

**Review by rayhan-ab — APPROVED** [review]

**Comment by rayhan-ab** [comment]
before you merge, you sure you add #minor to your commit message? i guess we don't need it since i don't see any version update in package and version.json so that the github actions won't automatically create a new tag

**Comment by aris-fm** [comment]
I just updated the PR with changelog and also version bump. Thanks for the review and the reminder

**Pull request merged**
