### PR TITLE
feat: add DB name validation

### PR DESCRIPTION
**Pull request by aris-fm**

### CODE REVIEW

**Comment by aris-fm** [comment]
After further checking, I found that the validation rule is identical with [KubelessHandler](https://github.com/AccelByte/justice-js-common-utils/blob/ddcf7570e05417c64e39238b76070656889322ae/src/lib/input-validation/validateKubelessHandler.ts#L23) one.

I think we have 3 options here:
1. Keep `validateKubelessHandler` and my proposed validation (`validateDatabaseName`) separate
2. Merge this 2 into a new generic validation, maybe `validateAlphanumericUnderscore`
3. Close this PR and using `validateKubelessHandler` to validate form that need to have **alphanumeric + underscore** rule

Any thought on this @yanuaracb @argaditya-ab ?

**Comment by argaditya-ab** [comment]
I prefer option 2, by giving a generic name it will make more sense to be used in another case as well. The downside is you need to change all `validateKubelessHandler` implementation to `validateAlphaNumericUnderscore`. But, if you think there are a lot of changes that need to be made in AP, then I think it's better to use option 1 instead. wdyt @yanuaracb ?

**Comment by yanuaracb** [comment]
I prefer the first option, I think it's ok.
the second option will be a breaking change, may be not much update in AP but still prefer not to do that.
another option is create that `validateAlphaNumericUnderscore` then use it for `validateKubelessHandler` so it's not a breaking change.

**Comment by aris-fm** [comment]
I also prefer the first option. Mainly because most other validation rule is also named by its feature (e.g. `validateCpuSize` `validateDockerImage`) rather than by its rule. And also, as of now the rule is still rarely used so it doesn't merit a dedicated rule yet.

**Review by yanuaracb — APPROVED** [review]

**Pull request merged**
